/*
 * File: pos_est_sf.c
 *
 *
 *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
 *
 *   This file is an S-function produced by the S-Function
 *   Builder which only recognizes certain fields.  Changes made
 *   outside these fields will be lost the next time the block is
 *   used to load, edit, and resave this file. This file will be overwritten
 *   by the S-function Builder block. If you want to edit this file by hand,
 *   you must change it only in the area defined as:
 *
 *        %%%-SFUNWIZ_defines_Changes_BEGIN
 *        #define NAME 'replacement text'
 *        %%% SFUNWIZ_defines_Changes_END
 *
 *   DO NOT change NAME--Change the 'replacement text' only.
 *
 *   For better compatibility with the Simulink Coder, the
 *   "wrapper" S-function technique is used.  This is discussed
 *   in the Simulink Coder's Manual in the Chapter titled,
 *   "Wrapper S-functions".
 *
 *  -------------------------------------------------------------------------
 * | See matlabroot/simulink/src/sfuntmpl_doc.c for a more detailed template |
 *  -------------------------------------------------------------------------
 *
 * Created: Thu Nov 27 17:34:49 2025
 */

#define S_FUNCTION_LEVEL               2
#define S_FUNCTION_NAME                pos_est_sf

/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */
#define NUM_INPUTS                     4

/* Input Port  0 */
#define IN_PORT_0_NAME                 Mag
#define INPUT_0_DIMS_ND                {1,1}
#define INPUT_0_NUM_ELEMS              1
#define INPUT_0_WIDTH                  1
#define INPUT_DIMS_0_COL               1
#define INPUT_0_DTYPE                  real_T
#define INPUT_0_COMPLEX                COMPLEX_NO
#define INPUT_0_UNIT                   ""
#define IN_0_BUS_BASED                 1
#define IN_0_BUS_NAME                  MAG_Bus
#define IN_0_DIMS                      1-D
#define INPUT_0_FEEDTHROUGH            1
#define IN_0_ISSIGNED                  0
#define IN_0_WORDLENGTH                8
#define IN_0_FIXPOINTSCALING           1
#define IN_0_FRACTIONLENGTH            9
#define IN_0_BIAS                      0
#define IN_0_SLOPE                     0.125

/* Input Port  1 */
#define IN_PORT_1_NAME                 Baro
#define INPUT_1_DIMS_ND                {1,1}
#define INPUT_1_NUM_ELEMS              1
#define INPUT_1_WIDTH                  1
#define INPUT_DIMS_1_COL               1
#define INPUT_1_DTYPE                  real32_T
#define INPUT_1_COMPLEX                COMPLEX_NO
#define INPUT_1_UNIT                   ""
#define IN_1_BUS_BASED                 1
#define IN_1_BUS_NAME                  PRESSURE_Bus
#define IN_1_DIMS                      1-D
#define INPUT_1_FEEDTHROUGH            1
#define IN_1_ISSIGNED                  0
#define IN_1_WORDLENGTH                8
#define IN_1_FIXPOINTSCALING           1
#define IN_1_FRACTIONLENGTH            9
#define IN_1_BIAS                      0
#define IN_1_SLOPE                     0.125

/* Input Port  2 */
#define IN_PORT_2_NAME                 GPS
#define INPUT_2_DIMS_ND                {1,1}
#define INPUT_2_NUM_ELEMS              1
#define INPUT_2_WIDTH                  1
#define INPUT_DIMS_2_COL               1
#define INPUT_2_DTYPE                  real_T
#define INPUT_2_COMPLEX                COMPLEX_NO
#define INPUT_2_UNIT                   ""
#define IN_2_BUS_BASED                 1
#define IN_2_BUS_NAME                  GPS_Bus
#define IN_2_DIMS                      1-D
#define INPUT_2_FEEDTHROUGH            1
#define IN_2_ISSIGNED                  0
#define IN_2_WORDLENGTH                8
#define IN_2_FIXPOINTSCALING           1
#define IN_2_FRACTIONLENGTH            9
#define IN_2_BIAS                      0
#define IN_2_SLOPE                     0.125

/* Input Port  3 */
#define IN_PORT_3_NAME                 IMU
#define INPUT_3_DIMS_ND                {1,1}
#define INPUT_3_NUM_ELEMS              1
#define INPUT_3_WIDTH                  1
#define INPUT_DIMS_3_COL               1
#define INPUT_3_DTYPE                  real_T
#define INPUT_3_COMPLEX                COMPLEX_NO
#define INPUT_3_UNIT                   ""
#define IN_3_BUS_BASED                 1
#define IN_3_BUS_NAME                  IMU_Bus
#define IN_3_DIMS                      1-D
#define INPUT_3_FEEDTHROUGH            1
#define IN_3_ISSIGNED                  0
#define IN_3_WORDLENGTH                8
#define IN_3_FIXPOINTSCALING           1
#define IN_3_FRACTIONLENGTH            9
#define IN_3_BIAS                      0
#define IN_3_SLOPE                     0.125
#define NUM_OUTPUTS                    5

/* Output Port  0 */
#define OUT_PORT_0_NAME                pos
#define OUTPUT_0_DIMS_ND               {3,1}
#define OUTPUT_0_NUM_ELEMS             3
#define OUTPUT_0_WIDTH                 3
#define OUTPUT_DIMS_0_COL              1
#define OUTPUT_0_DTYPE                 real_T
#define OUTPUT_0_COMPLEX               COMPLEX_NO
#define OUTPUT_0_UNIT                  ""
#define OUT_0_BUS_BASED                0
#define OUT_0_BUS_NAME
#define OUT_0_DIMS                     2-D
#define OUT_0_ISSIGNED                 1
#define OUT_0_WORDLENGTH               8
#define OUT_0_FIXPOINTSCALING          1
#define OUT_0_FRACTIONLENGTH           3
#define OUT_0_BIAS                     0
#define OUT_0_SLOPE                    0.125

/* Output Port  1 */
#define OUT_PORT_1_NAME                vel
#define OUTPUT_1_DIMS_ND               {3,1}
#define OUTPUT_1_NUM_ELEMS             3
#define OUTPUT_1_WIDTH                 3
#define OUTPUT_DIMS_1_COL              1
#define OUTPUT_1_DTYPE                 real_T
#define OUTPUT_1_COMPLEX               COMPLEX_NO
#define OUTPUT_1_UNIT                  ""
#define OUT_1_BUS_BASED                0
#define OUT_1_BUS_NAME
#define OUT_1_DIMS                     2-D
#define OUT_1_ISSIGNED                 1
#define OUT_1_WORDLENGTH               8
#define OUT_1_FIXPOINTSCALING          1
#define OUT_1_FRACTIONLENGTH           3
#define OUT_1_BIAS                     0
#define OUT_1_SLOPE                    0.125

/* Output Port  2 */
#define OUT_PORT_2_NAME                att
#define OUTPUT_2_DIMS_ND               {3,1}
#define OUTPUT_2_NUM_ELEMS             3
#define OUTPUT_2_WIDTH                 3
#define OUTPUT_DIMS_2_COL              1
#define OUTPUT_2_DTYPE                 real_T
#define OUTPUT_2_COMPLEX               COMPLEX_NO
#define OUTPUT_2_UNIT                  ""
#define OUT_2_BUS_BASED                0
#define OUT_2_BUS_NAME
#define OUT_2_DIMS                     2-D
#define OUT_2_ISSIGNED                 1
#define OUT_2_WORDLENGTH               8
#define OUT_2_FIXPOINTSCALING          1
#define OUT_2_FRACTIONLENGTH           3
#define OUT_2_BIAS                     0
#define OUT_2_SLOPE                    0.125

/* Output Port  3 */
#define OUT_PORT_3_NAME                att_acc_mag
#define OUTPUT_3_DIMS_ND               {3,1}
#define OUTPUT_3_NUM_ELEMS             3
#define OUTPUT_3_WIDTH                 3
#define OUTPUT_DIMS_3_COL              1
#define OUTPUT_3_DTYPE                 real_T
#define OUTPUT_3_COMPLEX               COMPLEX_NO
#define OUTPUT_3_UNIT                  ""
#define OUT_3_BUS_BASED                0
#define OUT_3_BUS_NAME
#define OUT_3_DIMS                     2-D
#define OUT_3_ISSIGNED                 1
#define OUT_3_WORDLENGTH               8
#define OUT_3_FIXPOINTSCALING          1
#define OUT_3_FRACTIONLENGTH           3
#define OUT_3_BIAS                     0
#define OUT_3_SLOPE                    0.125

/* Output Port  4 */
#define OUT_PORT_4_NAME                att_gyro
#define OUTPUT_4_DIMS_ND               {3,1}
#define OUTPUT_4_NUM_ELEMS             3
#define OUTPUT_4_WIDTH                 3
#define OUTPUT_DIMS_4_COL              1
#define OUTPUT_4_DTYPE                 real_T
#define OUTPUT_4_COMPLEX               COMPLEX_NO
#define OUTPUT_4_UNIT                  ""
#define OUT_4_BUS_BASED                0
#define OUT_4_BUS_NAME
#define OUT_4_DIMS                     2-D
#define OUT_4_ISSIGNED                 1
#define OUT_4_WORDLENGTH               8
#define OUT_4_FIXPOINTSCALING          1
#define OUT_4_FRACTIONLENGTH           3
#define OUT_4_BIAS                     0
#define OUT_4_SLOPE                    0.125
#define NPARAMS                        0
#define SAMPLE_TIME_0                  INHERITED_SAMPLE_TIME
#define NUM_DISC_STATES                0
#define DISC_STATES_IC                 [0]
#define NUM_CONT_STATES                0
#define CONT_STATES_IC                 [0]
#define SFUNWIZ_GENERATE_TLC           0
#define SOURCEFILES                    "__SFB__SRC_PATH .\algorithm\02_Common\COMMON__SFB__SRC_PATH .\algorithm\02_Common\RINGBUFFER__SFB__SRC_PATH .\algorithm\06_Application\00_Algorithm\Filter__SFB__SRC_PATH .\algorithm\06_Application\00_Algorithm__SFB__SRC_PATH .\algorithm\06_Application\04_Task__SFB__INC_PATH .\algorithm\02_Common\COMMON__SFB__INC_PATH .\algorithm\02_Common\RINGBUFFER__SFB__INC_PATH .\algorithm\06_Application\00_Algorithm\Filter__SFB__INC_PATH .\algorithm\06_Application\00_Algorithm__SFB__INC_PATH .\algorithm\06_Application\04_Task__SFB__INC_PATH .\algorithm__SFB__ringbuff.c__SFB__com_data.c__SFB__pro_common.c__SFB__filter.c__SFB__mahony.c__SFB__attitude_estimate.c__SFB__position_estimate.c__SFB__task_integrated_navigation.c"
#define PANELINDEX                     N/A
#define USE_SIMSTRUCT                  0
#define SHOW_COMPILE_STEPS             0
#define CREATE_DEBUG_MEXFILE           1
#define SAVE_CODE_ONLY                 1
#define SFUNWIZ_REVISION               3.0

/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
#include "simstruc.h"
#include "pos_est_sf_bus.h"

/*
 * Code Generation Environment flag (simulation or standalone target).
 */
static int_T isSimulationTarget;

/* Utility function prototypes. */
static int_T GetRTWEnvironmentMode(SimStruct *S);

/* Macro used to check if Simulation mode is set to accelerator */
#define isBusDWorkPresent              ( ( ( !ssRTWGenIsCodeGen(S) || isSimulationTarget ) && !ssIsExternalSim(S) ) || ssIsRapidAcceleratorActive(S) )

typedef struct {
  int_T offset;
  int_T elemSize;
  int_T numElems;
} busInfoStruct;

extern void pos_est_sf_Start_wrapper(void);
extern void pos_est_sf_Outputs_wrapper(const MAG_Bus *Mag,
  const PRESSURE_Bus *Baro,
  const GPS_Bus *GPS,
  const IMU_Bus *IMU,
  real_T *pos,
  real_T *vel,
  real_T *att,
  real_T *att_acc_mag,
  real_T *att_gyro);

/*====================*
 * S-function methods *
 *====================*/
/* Function: mdlInitializeSizes ===============================================
 * Abstract:
 *   Setup sizes of the various vectors.
 */
static void mdlInitializeSizes(SimStruct *S)
{
  DECL_AND_INIT_DIMSINFO(outputDimsInfo);
  ssSetNumSFcnParams(S, NPARAMS);
  if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
    return;                            /* Parameter mismatch will be reported by Simulink */
  }

  ssSetArrayLayoutForCodeGen(S, SS_COLUMN_MAJOR);
  ssSetOperatingPointCompliance(S, USE_DEFAULT_OPERATING_POINT);
  ssSetNumContStates(S, NUM_CONT_STATES);
  ssSetNumDiscStates(S, NUM_DISC_STATES);
  if (!ssSetNumInputPorts(S, NUM_INPUTS))
    return;

  /* Input Port 0 */

  /* Register MAG_Bus datatype for Input port 0 */
#if defined(MATLAB_MEX_FILE)

  if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {
    DTypeId dataTypeIdReg;
    ssRegisterTypeFromNamedObject(S, "MAG_Bus", &dataTypeIdReg);
    if (dataTypeIdReg == INVALID_DTYPE_ID)
      return;
    ssSetInputPortDataType(S, 0, dataTypeIdReg);
  }

#endif

  ssSetInputPortWidth(S, 0, INPUT_0_NUM_ELEMS);
  ssSetInputPortComplexSignal(S, 0, INPUT_0_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 0, INPUT_0_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 0, 1);/*direct input signal access*/
  ssSetBusInputAsStruct(S, 0, IN_0_BUS_BASED);
  ssSetInputPortBusMode(S, 0, SL_BUS_MODE);

  /* Input Port 1 */

  /* Register PRESSURE_Bus datatype for Input port 1 */
#if defined(MATLAB_MEX_FILE)

  if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {
    DTypeId dataTypeIdReg;
    ssRegisterTypeFromNamedObject(S, "PRESSURE_Bus", &dataTypeIdReg);
    if (dataTypeIdReg == INVALID_DTYPE_ID)
      return;
    ssSetInputPortDataType(S, 1, dataTypeIdReg);
  }

#endif

  ssSetInputPortWidth(S, 1, INPUT_1_NUM_ELEMS);
  ssSetInputPortComplexSignal(S, 1, INPUT_1_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 1, INPUT_1_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 1, 1);/*direct input signal access*/
  ssSetBusInputAsStruct(S, 1, IN_1_BUS_BASED);
  ssSetInputPortBusMode(S, 1, SL_BUS_MODE);

  /* Input Port 2 */

  /* Register GPS_Bus datatype for Input port 2 */
#if defined(MATLAB_MEX_FILE)

  if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {
    DTypeId dataTypeIdReg;
    ssRegisterTypeFromNamedObject(S, "GPS_Bus", &dataTypeIdReg);
    if (dataTypeIdReg == INVALID_DTYPE_ID)
      return;
    ssSetInputPortDataType(S, 2, dataTypeIdReg);
  }

#endif

  ssSetInputPortWidth(S, 2, INPUT_2_NUM_ELEMS);
  ssSetInputPortComplexSignal(S, 2, INPUT_2_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 2, INPUT_2_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 2, 1);/*direct input signal access*/
  ssSetBusInputAsStruct(S, 2, IN_2_BUS_BASED);
  ssSetInputPortBusMode(S, 2, SL_BUS_MODE);

  /* Input Port 3 */

  /* Register IMU_Bus datatype for Input port 3 */
#if defined(MATLAB_MEX_FILE)

  if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {
    DTypeId dataTypeIdReg;
    ssRegisterTypeFromNamedObject(S, "IMU_Bus", &dataTypeIdReg);
    if (dataTypeIdReg == INVALID_DTYPE_ID)
      return;
    ssSetInputPortDataType(S, 3, dataTypeIdReg);
  }

#endif

  ssSetInputPortWidth(S, 3, INPUT_3_NUM_ELEMS);
  ssSetInputPortComplexSignal(S, 3, INPUT_3_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 3, INPUT_3_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 3, 1);/*direct input signal access*/
  ssSetBusInputAsStruct(S, 3, IN_3_BUS_BASED);
  ssSetInputPortBusMode(S, 3, SL_BUS_MODE);

  /*
   * Configure the Units for Input Ports
   */
  if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {

#if defined(MATLAB_MEX_FILE)

    UnitId inUnitIdReg;
    ssRegisterUnitFromExpr(S, INPUT_0_UNIT, &inUnitIdReg);
    if (inUnitIdReg != INVALID_UNIT_ID) {
      ssSetInputPortUnit(S, 0, inUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for input port Mag of S-Function pos_est_sf");
      return;
    }

    ssRegisterUnitFromExpr(S, INPUT_1_UNIT, &inUnitIdReg);
    if (inUnitIdReg != INVALID_UNIT_ID) {
      ssSetInputPortUnit(S, 1, inUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for input port Baro of S-Function pos_est_sf");
      return;
    }

    ssRegisterUnitFromExpr(S, INPUT_2_UNIT, &inUnitIdReg);
    if (inUnitIdReg != INVALID_UNIT_ID) {
      ssSetInputPortUnit(S, 2, inUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for input port GPS of S-Function pos_est_sf");
      return;
    }

    ssRegisterUnitFromExpr(S, INPUT_3_UNIT, &inUnitIdReg);
    if (inUnitIdReg != INVALID_UNIT_ID) {
      ssSetInputPortUnit(S, 3, inUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for input port IMU of S-Function pos_est_sf");
      return;
    }

#endif

  }

  if (!ssSetNumOutputPorts(S, NUM_OUTPUTS))
    return;

  /* Output Port 0 */
  outputDimsInfo.numDims = 2;
  outputDimsInfo.width = OUTPUT_0_NUM_ELEMS;
  int_T out0Dims[] = OUTPUT_0_DIMS_ND;
  outputDimsInfo.dims = out0Dims;
  ssSetOutputPortDimensionInfo(S, 0, &outputDimsInfo);
  ssSetOutputPortDataType(S, 0, SS_DOUBLE);
  ssSetOutputPortComplexSignal(S, 0, OUTPUT_0_COMPLEX);

  /* Output Port 1 */
  outputDimsInfo.numDims = 2;
  outputDimsInfo.width = OUTPUT_1_NUM_ELEMS;
  int_T out1Dims[] = OUTPUT_1_DIMS_ND;
  outputDimsInfo.dims = out1Dims;
  ssSetOutputPortDimensionInfo(S, 1, &outputDimsInfo);
  ssSetOutputPortDataType(S, 1, SS_DOUBLE);
  ssSetOutputPortComplexSignal(S, 1, OUTPUT_1_COMPLEX);

  /* Output Port 2 */
  outputDimsInfo.numDims = 2;
  outputDimsInfo.width = OUTPUT_2_NUM_ELEMS;
  int_T out2Dims[] = OUTPUT_2_DIMS_ND;
  outputDimsInfo.dims = out2Dims;
  ssSetOutputPortDimensionInfo(S, 2, &outputDimsInfo);
  ssSetOutputPortDataType(S, 2, SS_DOUBLE);
  ssSetOutputPortComplexSignal(S, 2, OUTPUT_2_COMPLEX);

  /* Output Port 3 */
  outputDimsInfo.numDims = 2;
  outputDimsInfo.width = OUTPUT_3_NUM_ELEMS;
  int_T out3Dims[] = OUTPUT_3_DIMS_ND;
  outputDimsInfo.dims = out3Dims;
  ssSetOutputPortDimensionInfo(S, 3, &outputDimsInfo);
  ssSetOutputPortDataType(S, 3, SS_DOUBLE);
  ssSetOutputPortComplexSignal(S, 3, OUTPUT_3_COMPLEX);

  /* Output Port 4 */
  outputDimsInfo.numDims = 2;
  outputDimsInfo.width = OUTPUT_4_NUM_ELEMS;
  int_T out4Dims[] = OUTPUT_4_DIMS_ND;
  outputDimsInfo.dims = out4Dims;
  ssSetOutputPortDimensionInfo(S, 4, &outputDimsInfo);
  ssSetOutputPortDataType(S, 4, SS_DOUBLE);
  ssSetOutputPortComplexSignal(S, 4, OUTPUT_4_COMPLEX);

  /*
   * Configure the Units for Output Ports
   */
  if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {

#if defined(MATLAB_MEX_FILE)

    UnitId outUnitIdReg;
    ssRegisterUnitFromExpr(S, OUTPUT_0_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 0, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port pos of S-Function pos_est_sf");
      return;
    }

    ssRegisterUnitFromExpr(S, OUTPUT_1_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 1, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port vel of S-Function pos_est_sf");
      return;
    }

    ssRegisterUnitFromExpr(S, OUTPUT_2_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 2, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port att of S-Function pos_est_sf");
      return;
    }

    ssRegisterUnitFromExpr(S, OUTPUT_3_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 3, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port att_acc_mag of S-Function pos_est_sf");
      return;
    }

    ssRegisterUnitFromExpr(S, OUTPUT_4_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 4, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port att_gyro of S-Function pos_est_sf");
      return;
    }

#endif

  }

  if (ssRTWGenIsCodeGen(S)) {
    isSimulationTarget = GetRTWEnvironmentMode(S);
    if (isSimulationTarget == -1) {
      ssSetLocalErrorStatus(S,
                            " Unable to determine a valid code generation environment mode");
      return;
    }

    isSimulationTarget |= ssRTWGenIsModelReferenceSimTarget(S);
  }

  /* Set the number of dworks */
  if (!ssSetNumDWork(S, 4))
    return;

  /*
   * Configure the dwork 0 (MagBUS)
   */
#if defined(MATLAB_MEX_FILE)

  if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {
    DTypeId dataTypeIdReg;
    ssRegisterTypeFromNamedObject(S, "MAG_Bus", &dataTypeIdReg);
    if (dataTypeIdReg == INVALID_DTYPE_ID)
      return;
    if (isBusDWorkPresent) {
      ssSetDWorkDataType(S, 0, dataTypeIdReg);
    } else {
      ssSetDWorkDataType(S, 0, SS_POINTER);
    }
  }

#endif

  ssSetDWorkUsageType(S, 0, SS_DWORK_USED_AS_DWORK);
  ssSetDWorkName(S, 0, "MagBUS");
  ssSetDWorkWidth(S, 0, DYNAMICALLY_SIZED);
  ssSetDWorkComplexSignal(S, 0, COMPLEX_NO);

  /*
   * Configure the dwork 1 (BaroBUS)
   */
#if defined(MATLAB_MEX_FILE)

  if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {
    DTypeId dataTypeIdReg;
    ssRegisterTypeFromNamedObject(S, "PRESSURE_Bus", &dataTypeIdReg);
    if (dataTypeIdReg == INVALID_DTYPE_ID)
      return;
    if (isBusDWorkPresent) {
      ssSetDWorkDataType(S, 1, dataTypeIdReg);
    } else {
      ssSetDWorkDataType(S, 1, SS_POINTER);
    }
  }

#endif

  ssSetDWorkUsageType(S, 1, SS_DWORK_USED_AS_DWORK);
  ssSetDWorkName(S, 1, "BaroBUS");
  ssSetDWorkWidth(S, 1, DYNAMICALLY_SIZED);
  ssSetDWorkComplexSignal(S, 1, COMPLEX_NO);

  /*
   * Configure the dwork 2 (GPSBUS)
   */
#if defined(MATLAB_MEX_FILE)

  if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {
    DTypeId dataTypeIdReg;
    ssRegisterTypeFromNamedObject(S, "GPS_Bus", &dataTypeIdReg);
    if (dataTypeIdReg == INVALID_DTYPE_ID)
      return;
    if (isBusDWorkPresent) {
      ssSetDWorkDataType(S, 2, dataTypeIdReg);
    } else {
      ssSetDWorkDataType(S, 2, SS_POINTER);
    }
  }

#endif

  ssSetDWorkUsageType(S, 2, SS_DWORK_USED_AS_DWORK);
  ssSetDWorkName(S, 2, "GPSBUS");
  ssSetDWorkWidth(S, 2, DYNAMICALLY_SIZED);
  ssSetDWorkComplexSignal(S, 2, COMPLEX_NO);

  /*
   * Configure the dwork 3 (IMUBUS)
   */
#if defined(MATLAB_MEX_FILE)

  if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {
    DTypeId dataTypeIdReg;
    ssRegisterTypeFromNamedObject(S, "IMU_Bus", &dataTypeIdReg);
    if (dataTypeIdReg == INVALID_DTYPE_ID)
      return;
    if (isBusDWorkPresent) {
      ssSetDWorkDataType(S, 3, dataTypeIdReg);
    } else {
      ssSetDWorkDataType(S, 3, SS_POINTER);
    }
  }

#endif

  ssSetDWorkUsageType(S, 3, SS_DWORK_USED_AS_DWORK);
  ssSetDWorkName(S, 3, "IMUBUS");
  ssSetDWorkWidth(S, 3, DYNAMICALLY_SIZED);
  ssSetDWorkComplexSignal(S, 3, COMPLEX_NO);
  ssSetNumPWork(S, 0);
  ssSetNumSampleTimes(S, 1);
  ssSetNumRWork(S, 0);
  ssSetNumIWork(S, 0);
  ssSetNumModes(S, 0);
  ssSetNumNonsampledZCs(S, 0);
  ssSetSimulinkVersionGeneratedIn(S, "24.1");

  /* Take care when specifying exception free code - see sfuntmpl_doc.c */
  ssSetRuntimeThreadSafetyCompliance(S, RUNTIME_THREAD_SAFETY_COMPLIANCE_FALSE);
  ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
                   SS_OPTION_WORKS_WITH_CODE_REUSE));
}

#if defined(MATLAB_MEX_FILE)
#define MDL_SET_INPUT_PORT_DIMENSION_INFO

static void mdlSetInputPortDimensionInfo(SimStruct *S,
  int_T port,
  const DimsInfo_T *dimsInfo)
{
  if (!ssSetInputPortDimensionInfo(S, port, dimsInfo))
    return;
}

#endif

#define MDL_SET_OUTPUT_PORT_DIMENSION_INFO
#if defined(MDL_SET_OUTPUT_PORT_DIMENSION_INFO)

static void mdlSetOutputPortDimensionInfo(SimStruct *S,
  int_T port,
  const DimsInfo_T *dimsInfo)
{
  if (!ssSetOutputPortDimensionInfo(S, port, dimsInfo))
    return;
}

#endif

#define MDL_SET_DEFAULT_PORT_DIMENSION_INFO

static void mdlSetDefaultPortDimensionInfo(SimStruct *S)
{
  DECL_AND_INIT_DIMSINFO(portDimsInfo);
  int_T dims[2];

  /* Setting default dimensions for output port 0 */
  portDimsInfo.width = OUTPUT_0_NUM_ELEMS;
  dims[0] = OUTPUT_0_NUM_ELEMS;
  dims[1] = 1;
  portDimsInfo.numDims = 2;
  if (ssGetOutputPortNumDimensions(S, 0) == (-1)) {
    ssSetOutputPortDimensionInfo(S, 0, &portDimsInfo);
  }

  /* Setting default dimensions for output port 1 */
  portDimsInfo.width = OUTPUT_1_NUM_ELEMS;
  dims[0] = OUTPUT_1_NUM_ELEMS;
  dims[1] = 1;
  portDimsInfo.numDims = 2;
  if (ssGetOutputPortNumDimensions(S, 1) == (-1)) {
    ssSetOutputPortDimensionInfo(S, 1, &portDimsInfo);
  }

  /* Setting default dimensions for output port 2 */
  portDimsInfo.width = OUTPUT_2_NUM_ELEMS;
  dims[0] = OUTPUT_2_NUM_ELEMS;
  dims[1] = 1;
  portDimsInfo.numDims = 2;
  if (ssGetOutputPortNumDimensions(S, 2) == (-1)) {
    ssSetOutputPortDimensionInfo(S, 2, &portDimsInfo);
  }

  /* Setting default dimensions for output port 3 */
  portDimsInfo.width = OUTPUT_3_NUM_ELEMS;
  dims[0] = OUTPUT_3_NUM_ELEMS;
  dims[1] = 1;
  portDimsInfo.numDims = 2;
  if (ssGetOutputPortNumDimensions(S, 3) == (-1)) {
    ssSetOutputPortDimensionInfo(S, 3, &portDimsInfo);
  }

  /* Setting default dimensions for output port 4 */
  portDimsInfo.width = OUTPUT_4_NUM_ELEMS;
  dims[0] = OUTPUT_4_NUM_ELEMS;
  dims[1] = 1;
  portDimsInfo.numDims = 2;
  if (ssGetOutputPortNumDimensions(S, 4) == (-1)) {
    ssSetOutputPortDimensionInfo(S, 4, &portDimsInfo);
  }

  return;
}

/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Specifiy  the sample time.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
  ssSetSampleTime(S, 0, SAMPLE_TIME_0);
  ssSetModelReferenceSampleTimeDefaultInheritance(S);
  ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_SET_INPUT_PORT_DATA_TYPE

static void mdlSetInputPortDataType(SimStruct *S, int port, DTypeId dType)
{
  ssSetInputPortDataType(S, 0, dType);
}

#define MDL_SET_OUTPUT_PORT_DATA_TYPE

static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType)
{
  ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES

static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
  ssSetInputPortDataType(S, 0, SS_DOUBLE);
  ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}

#define MDL_SET_WORK_WIDTHS
#if defined(MDL_SET_WORK_WIDTHS) && defined(MATLAB_MEX_FILE)

static void mdlSetWorkWidths(SimStruct *S)
{
  /* Set the width of DWork(s) used for marshalling the IOs */
  if (isBusDWorkPresent) {
    /* Update dwork 0 */
    ssSetDWorkWidth(S, 0, ssGetInputPortWidth(S, 0));

    /* Update dwork 1 */
    ssSetDWorkWidth(S, 1, ssGetInputPortWidth(S, 1));

    /* Update dwork 2 */
    ssSetDWorkWidth(S, 2, ssGetInputPortWidth(S, 2));

    /* Update dwork 3 */
    ssSetDWorkWidth(S, 3, ssGetInputPortWidth(S, 3));
  }
}

#endif

#define MDL_START                                                /* Change to #undef to remove function */
#if defined(MDL_START)

/* Function: mdlStart =======================================================
 * Abstract:
 *    This function is called once at start of model execution. If you
 *    have states that should be initialized once, this is the place
 *    to do it.
 */
static void mdlStart(SimStruct *S)
{
  /* Bus Information */
  slDataTypeAccess *dta = ssGetDataTypeAccess(S);
  const char *bpath = ssGetPath(S);
  DTypeId AccId = ssGetDataTypeId(S,"Acc");
  DTypeId GPS_BusId = ssGetDataTypeId(S,"GPS_Bus");
  DTypeId GyroId = ssGetDataTypeId(S,"Gyro");
  DTypeId IMU_BusId = ssGetDataTypeId(S,"IMU_Bus");
  DTypeId MAG_BusId = ssGetDataTypeId(S,"MAG_Bus");
  DTypeId PRESSURE_BusId = ssGetDataTypeId(S,"PRESSURE_Bus");
  busInfoStruct *busInfo = (busInfoStruct *)malloc(27*sizeof(busInfoStruct));
  if (busInfo==NULL) {
    ssSetLocalErrorStatus(S, "Memory allocation failure");
    return;
  }

  /*offsets info for all unique bus structures*/
  busInfo[0].offset = dtaGetDataTypeElementOffset(dta, bpath, MAG_BusId, 0);
  busInfo[0].elemSize = dtaGetDataTypeSize(dta, bpath, SS_DOUBLE);
  busInfo[0].numElems = 1;
  busInfo[1].offset = dtaGetDataTypeElementOffset(dta, bpath, MAG_BusId, 1);
  busInfo[1].elemSize = dtaGetDataTypeSize(dta, bpath, SS_DOUBLE);
  busInfo[1].numElems = 1;
  busInfo[2].offset = dtaGetDataTypeElementOffset(dta, bpath, MAG_BusId, 2);
  busInfo[2].elemSize = dtaGetDataTypeSize(dta, bpath, SS_DOUBLE);
  busInfo[2].numElems = 1;
  busInfo[3].offset = dtaGetDataTypeElementOffset(dta, bpath, PRESSURE_BusId, 0);
  busInfo[3].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[3].numElems = 1;
  busInfo[4].offset = dtaGetDataTypeElementOffset(dta, bpath, GPS_BusId, 0);
  busInfo[4].elemSize = dtaGetDataTypeSize(dta, bpath, SS_DOUBLE);
  busInfo[4].numElems = 1;
  busInfo[5].offset = dtaGetDataTypeElementOffset(dta, bpath, GPS_BusId, 1);
  busInfo[5].elemSize = dtaGetDataTypeSize(dta, bpath, SS_DOUBLE);
  busInfo[5].numElems = 1;
  busInfo[6].offset = dtaGetDataTypeElementOffset(dta, bpath, GPS_BusId, 2);
  busInfo[6].elemSize = dtaGetDataTypeSize(dta, bpath, SS_DOUBLE);
  busInfo[6].numElems = 1;
  busInfo[7].offset = dtaGetDataTypeElementOffset(dta, bpath, GPS_BusId, 3);
  busInfo[7].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[7].numElems = 1;
  busInfo[8].offset = dtaGetDataTypeElementOffset(dta, bpath, GPS_BusId, 4);
  busInfo[8].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[8].numElems = 1;
  busInfo[9].offset = dtaGetDataTypeElementOffset(dta, bpath, GPS_BusId, 5);
  busInfo[9].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[9].numElems = 1;
  busInfo[10].offset = dtaGetDataTypeElementOffset(dta, bpath, GPS_BusId, 6);
  busInfo[10].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[10].numElems = 1;
  busInfo[11].offset = dtaGetDataTypeElementOffset(dta, bpath, GPS_BusId, 7);
  busInfo[11].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[11].numElems = 1;
  busInfo[12].offset = dtaGetDataTypeElementOffset(dta, bpath, GPS_BusId, 8);
  busInfo[12].elemSize = dtaGetDataTypeSize(dta, bpath, SS_DOUBLE);
  busInfo[12].numElems = 1;
  busInfo[13].offset = dtaGetDataTypeElementOffset(dta, bpath, GPS_BusId, 9);
  busInfo[13].elemSize = dtaGetDataTypeSize(dta, bpath, SS_DOUBLE);
  busInfo[13].numElems = 1;
  busInfo[14].offset = dtaGetDataTypeElementOffset(dta, bpath, GPS_BusId, 10);
  busInfo[14].elemSize = dtaGetDataTypeSize(dta, bpath, SS_UINT8);
  busInfo[14].numElems = 1;
  busInfo[15].offset = dtaGetDataTypeElementOffset(dta, bpath, IMU_BusId, 0);
  busInfo[15].elemSize = dtaGetDataTypeSize(dta, bpath, AccId);
  busInfo[15].numElems = 1;
  busInfo[16].offset = dtaGetDataTypeElementOffset(dta, bpath, AccId, 0);
  busInfo[16].elemSize = dtaGetDataTypeSize(dta, bpath, SS_DOUBLE);
  busInfo[16].numElems = 1;
  busInfo[17].offset = dtaGetDataTypeElementOffset(dta, bpath, AccId, 1);
  busInfo[17].elemSize = dtaGetDataTypeSize(dta, bpath, SS_DOUBLE);
  busInfo[17].numElems = 1;
  busInfo[18].offset = dtaGetDataTypeElementOffset(dta, bpath, AccId, 2);
  busInfo[18].elemSize = dtaGetDataTypeSize(dta, bpath, SS_DOUBLE);
  busInfo[18].numElems = 1;
  busInfo[19].offset = dtaGetDataTypeElementOffset(dta, bpath, IMU_BusId, 1);
  busInfo[19].elemSize = dtaGetDataTypeSize(dta, bpath, GyroId);
  busInfo[19].numElems = 1;
  busInfo[20].offset = dtaGetDataTypeElementOffset(dta, bpath, GyroId, 0);
  busInfo[20].elemSize = dtaGetDataTypeSize(dta, bpath, SS_DOUBLE);
  busInfo[20].numElems = 1;
  busInfo[21].offset = dtaGetDataTypeElementOffset(dta, bpath, GyroId, 1);
  busInfo[21].elemSize = dtaGetDataTypeSize(dta, bpath, SS_DOUBLE);
  busInfo[21].numElems = 1;
  busInfo[22].offset = dtaGetDataTypeElementOffset(dta, bpath, GyroId, 2);
  busInfo[22].elemSize = dtaGetDataTypeSize(dta, bpath, SS_DOUBLE);
  busInfo[22].numElems = 1;
  busInfo[23].elemSize = dtaGetDataTypeSize(dta, bpath, MAG_BusId);
  busInfo[23].numElems = ssGetInputPortWidth(S, 0);
  busInfo[24].elemSize = dtaGetDataTypeSize(dta, bpath, PRESSURE_BusId);
  busInfo[24].numElems = ssGetInputPortWidth(S, 1);
  busInfo[25].elemSize = dtaGetDataTypeSize(dta, bpath, GPS_BusId);
  busInfo[25].numElems = ssGetInputPortWidth(S, 2);
  busInfo[26].elemSize = dtaGetDataTypeSize(dta, bpath, IMU_BusId);
  busInfo[26].numElems = ssGetInputPortWidth(S, 3);
  ssSetUserData(S, busInfo);

  /* Allocate memory for arrays or nested arrays of buses DWork pointers */
  pos_est_sf_Start_wrapper();
}

#endif                                 /*  MDL_START */

/* Function: mdlOutputs =======================================================
 *
 */
static void mdlOutputs(SimStruct *S, int_T tid)
{
  const char *Mag = (char *) ssGetInputPortSignal(S, 0);
  const char *Baro = (char *) ssGetInputPortSignal(S, 1);
  const char *GPS = (char *) ssGetInputPortSignal(S, 2);
  const char *IMU = (char *) ssGetInputPortSignal(S, 3);
  real_T *pos = (real_T *) ssGetOutputPortRealSignal(S, 0);
  real_T *vel = (real_T *) ssGetOutputPortRealSignal(S, 1);
  real_T *att = (real_T *) ssGetOutputPortRealSignal(S, 2);
  real_T *att_acc_mag = (real_T *) ssGetOutputPortRealSignal(S, 3);
  real_T *att_gyro = (real_T *) ssGetOutputPortRealSignal(S, 4);
  busInfoStruct* busInfo = (busInfoStruct *) ssGetUserData(S);

  /* Temporary bus copy declarations */
  MAG_Bus _MagBUS;
  PRESSURE_Bus _BaroBUS;
  GPS_Bus _GPSBUS;
  IMU_Bus _IMUBUS;
  slDataTypeAccess *dta = ssGetDataTypeAccess(S);
  const char *bpath = ssGetPath(S);

  /*Copy from Simulink to bus structure*/

  /*Copy from Simulink to _MagBUS for Input port 0*/
  (_MagBUS).X = *((real_T*)((char *) Mag + busInfo[0].offset));
  (_MagBUS).Y = *((real_T*)((char *) Mag + busInfo[1].offset));
  (_MagBUS).Z = *((real_T*)((char *) Mag + busInfo[2].offset));

  /*Copy from Simulink to _BaroBUS for Input port 1*/
  (_BaroBUS).Pressure = *((real32_T*)((char *) Baro + busInfo[3].offset));

  /*Copy from Simulink to _GPSBUS for Input port 2*/
  (_GPSBUS).Lat = *((real_T*)((char *) GPS + busInfo[4].offset));
  (_GPSBUS).Lon = *((real_T*)((char *) GPS + busInfo[5].offset));
  (_GPSBUS).Alt = *((real_T*)((char *) GPS + busInfo[6].offset));
  (_GPSBUS).VelN = *((real32_T*)((char *) GPS + busInfo[7].offset));
  (_GPSBUS).VelE = *((real32_T*)((char *) GPS + busInfo[8].offset));
  (_GPSBUS).VelD = *((real32_T*)((char *) GPS + busInfo[9].offset));
  (_GPSBUS).eph = *((real32_T*)((char *) GPS + busInfo[10].offset));
  (_GPSBUS).epv = *((real32_T*)((char *) GPS + busInfo[11].offset));
  (_GPSBUS).GotP = *((real_T*)((char *) GPS + busInfo[12].offset));
  (_GPSBUS).GotV = *((real_T*)((char *) GPS + busInfo[13].offset));
  (_GPSBUS).satellites_used = *((uint8_T*)((char *) GPS + busInfo[14].offset));

  /*Copy from Simulink to _IMUBUS for Input port 3*/
  (_IMUBUS).Acc.X = *((real_T*)((char *) IMU + busInfo[15].offset + busInfo[16].
    offset));
  (_IMUBUS).Acc.Y = *((real_T*)((char *) IMU + busInfo[15].offset + busInfo[17].
    offset));
  (_IMUBUS).Acc.Z = *((real_T*)((char *) IMU + busInfo[15].offset + busInfo[18].
    offset));
  (_IMUBUS).Gyro.X = *((real_T*)((char *) IMU + busInfo[19].offset + busInfo[20]
    .offset));
  (_IMUBUS).Gyro.Y = *((real_T*)((char *) IMU + busInfo[19].offset + busInfo[21]
    .offset));
  (_IMUBUS).Gyro.Z = *((real_T*)((char *) IMU + busInfo[19].offset + busInfo[22]
    .offset));
  pos_est_sf_Outputs_wrapper(&_MagBUS, &_BaroBUS, &_GPSBUS, &_IMUBUS, pos, vel,
    att, att_acc_mag, att_gyro);

  /*Copy from bus structure to Simulink*/
}

/* Function: mdlTerminate =====================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.  For example, if memory was
 *    allocated in mdlStart, this is the place to free it.
 */
static void mdlTerminate(SimStruct *S)
{
  /* Free stored bus information */
  busInfoStruct *busInfo = (busInfoStruct *) ssGetUserData(S);
  if (busInfo != NULL) {
    free(busInfo);
  }

  if (!isBusDWorkPresent) {
  }
}

static int_T GetRTWEnvironmentMode(SimStruct *S)
{
  int_T status = -1;
  mxArray *plhs[1];
  mxArray *prhs[1];
  mxArray * err;

  /*
   * Get the name of the Simulink block diagram
   */
  prhs[0] = mxCreateString(ssGetBlockDiagramName(S));
  plhs[0] = NULL;

  /*
   * Call "isSimulationTarget = rtwenvironmentmode(modelName)" in MATLAB
   */
  err = mexCallMATLABWithTrap(1, plhs, 1, prhs, "rtwenvironmentmode");
  mxDestroyArray(prhs[0]);

  /*
   * Set the error status if an error occurred
   */
  if (err) {
    if (plhs[0]) {
      mxDestroyArray(plhs[0]);
      plhs[0] = NULL;
    }

    ssSetLocalErrorStatus(S,
                          "Unknown error during call to 'rtwenvironmentmode'.");
    return -1;
  }

  /*
   * Get the value returned by rtwenvironmentmode(modelName)
   */
  if (plhs[0]) {
    status = (int_T) (mxGetScalar(plhs[0]) != 0);
    mxDestroyArray(plhs[0]);
    plhs[0] = NULL;
  }

  return (status);
}

#ifdef MATLAB_MEX_FILE                 /* Is this file being compiled as a MEX-file? */
#include "simulink.c"                  /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"                   /* Code generation registration function */
#endif
