/* Generated by S-function Builder */
#ifndef _POS_EST_SF_BUS_H_
#define _POS_EST_SF_BUS_H_
/* Read only - STARTS */
#ifdef MATLAB_MEX_FILE
#include "tmwtypes.h"
#else
#include "rtwtypes.h"
#endif




#ifndef DEFINED_TYPEDEF_FOR_MAG_Bus_
#define DEFINED_TYPEDEF_FOR_MAG_Bus_ 
typedef struct {
  real_T X;
  real_T Y;
  real_T Z;
} MAG_Bus;
#endif


#ifndef DEFINED_TYPEDEF_FOR_PRESSURE_Bus_
#define DEFINED_TYPEDEF_FOR_PRESSURE_Bus_ 
typedef struct {
  real32_T Pressure;
} PRESSURE_Bus;
#endif


#ifndef DEFINED_TYPEDEF_FOR_GPS_Bus_
#define DEFINED_TYPEDEF_FOR_GPS_Bus_ 
typedef struct {
  real_T Lat;
  real_T Lon;
  real_T Alt;
  real32_T VelN;
  real32_T VelE;
  real32_T VelD;
  real32_T eph;
  real32_T epv;
  real_T GotP;
  real_T GotV;
  uint8_T satellites_used;
} GPS_Bus;
#endif


#ifndef DEFINED_TYPEDEF_FOR_Gyro_
#define DEFINED_TYPEDEF_FOR_Gyro_ 
typedef struct {
  real_T X;
  real_T Y;
  real_T Z;
} Gyro;
#endif


#ifndef DEFINED_TYPEDEF_FOR_Acc_
#define DEFINED_TYPEDEF_FOR_Acc_ 
typedef struct {
  real_T X;
  real_T Y;
  real_T Z;
} Acc;
#endif


#ifndef DEFINED_TYPEDEF_FOR_IMU_Bus_
#define DEFINED_TYPEDEF_FOR_IMU_Bus_ 
typedef struct {
  Acc Acc;
  Gyro Gyro;
} IMU_Bus;
#endif

/* Read only - ENDS */


#endif
