/* Generated by S-function Builder */
#ifndef _POS_EST_SF_BUS_H_
#define _POS_EST_SF_BUS_H_
/* Read only - STARTS */
#ifdef MATLAB_MEX_FILE
#include "tmwtypes.h"
#else
#include "rtwtypes.h"
#endif




#ifndef DEFINED_TYPEDEF_FOR_Gyro_
#define DEFINED_TYPEDEF_FOR_Gyro_ 
typedef struct {
  real_T X;
  real_T Y;
  real_T Z;
} Gyro;
#endif


#ifndef DEFINED_TYPEDEF_FOR_Acc_
#define DEFINED_TYPEDEF_FOR_Acc_ 
typedef struct {
  real_T X;
  real_T Y;
  real_T Z;
} Acc;
#endif


#ifndef DEFINED_TYPEDEF_FOR_IMU_Bus_
#define DEFINED_TYPEDEF_FOR_IMU_Bus_ 
typedef struct {
  Acc Acc;
  Gyro Gyro;
} IMU_Bus;
#endif

/* Read only - ENDS */


#endif
